### ISSUE TITLE
Mamba for temporal action localization

### ISSUE THREAD

**Issue by PeterJoe15** [OpenGVLab/video-mamba-suite#1]
Great job! Where can I find videoMamba for temporal action localization?

**Comment by cg1177** [comment]
I am sorting out this part of codes. It will be released in this weekend.

**Comment by cg1177** [comment]
Hello, I have updated the repo to support TAL tasks. You can easily taste it. If there exist bugs, you can open a new issue.

**Comment by PeterJoe15** [comment]
Thank you，dear author could you please share the version of mamba

**Comment by cg1177** [comment]
@PeterJoe15  I have added the `preliminary installation` part to the main readme. May be you can try it.
