### ISSUE TITLE
can't find 'vim_t_midclstok_76p1acc.pth' in action recognition task

### ISSUE THREAD

**Issue by cheng1397** [OpenGVLab/video-mamba-suite#17]
Thank you for your amazing work!
trying to run the code for the action recognition task. I tried to run 
"python run_class_finetuning.py \
        --model vivim_tiny \
        --data_path /root/autodl-tmp/video-mamba-suite/k400_dataset \
        --prefix /root/autodl-tmp/video-mamba-suite/k400_dataset \
        --data_set 'Kinetics_sparse' \
        --split ',' \
        --nb_classes 400 \
        --log_dir output \
        --output_dir output \
        --batch_size 32 \
        --num_sample 2 \
        --input_size 224 \
        --short_side_size 224 \
        --save_ckpt_freq 100 \
        --num_frames 16 \
        --num_workers 12 \
        --warmup_epochs 5 \
        --tubelet_size 1 \
        --epochs 70 \
        --lr 2e-4 \
        --drop_path 0.1 \
        --aa rand-m5-n2-mstd0.25-inc1 \
        --opt adamw \
        --opt_betas 0.9 0.999 \
        --weight_decay 0.1 \
        --test_num_segment 4 \
        --test_num_crop 3 \
        --dist_eval \
        --test_best \
        --bf16"
 however, it says "FileNotFoundError: [Errno 2] No such file or directory: '/mnt/petrelfs/chenguo/pretrained_models/vim/Vim-tiny-midclstok/vim_t_midclstok_76p1acc.pth'” 
could there be a missiong pth file? Thank you for your excellent work again.

**Comment by CrazyGeG** [comment]
Hi, could you please tell me how did you solve this problem?
