### ISSUE TITLE
video temporal grounding inference issue

### ISSUE THREAD

**Issue by PeterJoe15** [OpenGVLab/video-mamba-suite#9]
when using code of inference ，tensors are not in one device.

**Comment by PeterJoe15** [comment]
![f9828cf1d688a86cbb80bcce37401d8](https://github.com/OpenGVLab/video-mamba-suite/assets/154965158/e8d3e61a-9b79-4ea6-a682-5ad3f824f9ee)

**Comment by cg1177** [comment]
I'll confirm and get back to you shortly.

**Comment by cg1177** [comment]
yuo should ensure model parameters and tensor stay GPU at the same time.
